name: Workflow for Codecov example-java-maven
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 19
        uses: actions/setup-java@v4
        with:
          java-version: "19"
          distribution: "temurin"
          cache: "gradle"
          # cache-dependency-path: "build.gradle.kts"
      - name: Before Install
        run: |
          cd cviceni
          cd SmartCaffe
          chmod +x gradlew
          chmod +x gradle/wrapper/gradle-wrapper.jar
      - name: Test and collect coverage
        run: |
          cd cviceni
          cd SmartCaffe
          ./gradlew build
          ./gradlew test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_ORG_TOKEN }}
